name: Deploy Docker Image

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    # 部署到Railway
    - name: Deploy to Railway
      uses: railwayapp/actions/cli@master
      with:
        railway_token: ${{ secrets.RAILWAY_TOKEN }}
        railway_service: ${{ secrets.RAILWAY_SERVICE }}
    
    
